mtcars dataset:
  file: functions/mtcars.r
  output: mtcars.xlsx
plot chart:
  file: functions/plot.r
  output: plot.pdf
  form: forms/plot.yml
survey dataset:
  file: functions/survey.r
  output: survey.xlsx
