Cars data:
  file: functions/mtcars.r
  output: mtcars.xlsx
Plot Chart:
  file: functions/plot.r
  output: plot.pdf
  form: forms/plot.yml
  help: Please fill in all necessary details
Survey data:
  file: functions/survey.r
  output: survey.xlsx
  readme: ../README.md
